version: 0.2

env:
  variables:
    AWS_REGION: "eu-central-1"
    IMAGE_NAME: "sample-repo"
    ECR_REGISTRY: "863518438805.dkr.ecr.eu-central-1.amazonaws.com"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - echo "ECR Registry: $ECR_REGISTRY"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_NAME .
      - echo "Tagging Docker image..."
      - docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REGISTRY/$IMAGE_NAME:latest
      - echo "Build and push completed successfully!"

artifacts:
  files:
    - "**/*"
